---
- include_vars: vars_main.yml

- name: Instalando docker + docker-compose
  apt:
    name: "{{ item }}"
    update_cache: true
    cache_valid_time: 3600
  with_items: "{{ docker_packages }}"  
  register: docker_installation  

- name: Agregando usuario a grupo
  shell: "usermod -aG docker {{ ansible_env.SUDO_USER }}"
  when: ansible_env.SUDO_USER != 'root'

- name: Reiniciando conexion ssh para que tome los cambios 
  meta: "reset_connection"

- name: Enviar notificación a Telegram
  uri:
    url: "https://api.telegram.org/bot{{ telegram_token }}/sendMessage"
    method: POST
    body:
      chat_id: "{{ telegram_chat_id }}"
      text: "La instalación de {{ docker_packages }} en el equipo {{ inventory_hostname }} se ha completado correctamente."
    body_format: json
  when: docker_installation.changed