---
- include_vars: vars_main.yml

- name: Actualizar Ubuntu/Debian
  when: ansible_facts['os_family'] == 'Debian'
  ansible.builtin.apt:
    upgrade: dist
    autoremove: true
    update_cache: true

- name: Chequea si necesita reinicio
  when: ansible_facts['os_family'] == 'Debian'
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: ubuntu_reboot_required

- name: Reinicia Ubuntu/Debian
  when: ubuntu_reboot_required.stat.exists | default(false)
  ansible.builtin.reboot:
    reboot_timeout: 600 

- name: Actualizar Centos/Rocky
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.dnf:
    state: latest

- name: Chequea si necesita reinicio
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: redhat_reboot_required

- name: Reinicia Centos/Rocky
  when: redhat_reboot_required.stat.exists | default(false)
  ansible.builtin.reboot:
    reboot_timeout: 600 
